### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'output_attentions'

### ISSUE THREAD

**Issue by ameamefans** [PxYu/Pretraining-CLIR#1] opened 2022-04-11 05:29 UTC
Hi, I am getting the following error when running train.py

Traceback (most recent call last):
  File "D:/py/CLIR/Pretraining-CLIR-master/train.py", line 156, in <module>
    main(params)
  File "D:/py/CLIR/Pretraining-CLIR-master/train.py", line 135, in main
    trainer.qlm_step(lang_pair, params.lambda_qlm)
  File "D:\py\CLIR\Pretraining-CLIR-master\trainer.py", line 340, in qlm_step
    outputs = self.model(inputs)
  File "D:\anaconda3\envs\CLIR\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\py\CLIR\Pretraining-CLIR-master\BertForXLRetrieval.py", line 46, in forward
    return self.forward_mlm(**kwargs)
  File "D:\py\CLIR\Pretraining-CLIR-master\BertForXLRetrieval.py", line 87, in forward_mlm
    output_hidden_states=output_hidden_states,
  File "D:\anaconda3\envs\CLIR\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'output_attentions'

Any idea how to solve this error? Thanks.

**Comment by PxYu** [comment] 2022-04-11 14:50
Hello! Thanks for opening this issue. 

This looks like a version problem with the Huggingface Transformer library. What version are you currently on? 

I cannot recall the exact version on which this was developed, but I suggest you try v3.0.0 to v3.2.0, based on the time of development (https://github.com/huggingface/transformers/releases?page=6).

Let me know how that works! Sorry for the inconvenience.

**Comment by stoicboyoversea** [comment] 2022-04-11 23:32
I can confirm that Transformer v3.4.0 works flawlessly on my side.

**Comment by ameamefans** [comment] 2022-04-12 02:02
Thank you very much for your reply, now I use transfomers v3.4.0, this problem has been solved. And I try to solve another problem, since I only have a GPU with 6g memory, it will cause memory overflow when training, I will try to change my hyperparameter settings.

**Comment by PxYu** [comment] 2022-04-13 02:34
@stoicboyoversea @ameamefans Thank you for your comments! It seems that the issue has been resolved. I'm closing this issue!

**Closed as completed by PxYu** 2022-04-13 02:34 UTC
